### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by TheMas3212** [Ownasaurus/TASLink#28]
Just wondering if there are any thoughts for or against trying to port TASLink to use python3?

**Comment by Ownasaurus** [comment]
When this code was originally created, I was told by TheAxeMan to keep in in python2 because he was going to add a GUI, and he was very comfortable with py2. Unfortunately, that never came to fruition. I would speak to DwangoAC about this to see if TheAxeMan might do this eventually or not.

Aside from that, I have no strong opinion either way other than "if it ain't broke don't fix"

**Comment by TheMas3212** [comment]
ok, i guess il bring in up to DwangoAC after SGDQ is over
im sort of planning to see if i can clean up the script a bit into modules so it instead of just 1 massive file 1500 lines long and i figure if im going to do that i might see if i can get it working with python3

**Comment by Ownasaurus** [comment]
Any updated status on this?

**Comment by TheMas3212** [comment]
not really no, you can close the issue if you want
